In [159]:
import pandas as pd
import numpy as np

In [160]:
customers=pd.read_csv("olist_customers_dataset.csv")

In [161]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

### columns:

customer_id =  
key to the orders dataset. Each order has a unique customer_id.

customer_unique_id  =  
unique identifier of a customer.

customer_zip_code_prefix =  
first five digits of customer zip code

customer_city  =  
customer city name

customer_state  =  
customer state


#### new column
state_name =  
state name using customer_state

In [162]:
# the types of each columns
customers.dtypes

customer_id                 object
customer_unique_id          object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object

In [163]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [164]:
#To make a new colum to state name
customers["customer_state"].unique()

array(['SP', 'SC', 'MG', 'PR', 'RJ', 'RS', 'PA', 'GO', 'ES', 'BA', 'MA',
       'MS', 'CE', 'DF', 'RN', 'PE', 'MT', 'AM', 'AP', 'AL', 'RO', 'PB',
       'TO', 'PI', 'AC', 'SE', 'RR'], dtype=object)

In [165]:
# collect the names of each state :
state_names = {
    'AC': 'Acre',
    'AL': 'Alagoas',
    'AP': 'Amapa',
    'AM': 'Amazonas',
    'BA': 'Bahia',
    'CE': 'Ceara',
    'ES': 'Espirito Santo',
    'GO': 'Goias',
    'MA': 'Maranhao',
    'MT': 'Mato Grosso',
    'MS': 'Mato Grosso do Sul',
    'MG': 'Minas Gerais',
    'PA': 'Para',
    'PB': 'Paraiba',
    'PR': 'Parana',
    'PE': 'Pernambuco',
    'PI': 'Piaui',
    'RJ': 'Rio de Janeiro',
    'RN': 'Rio Grande do Norte',
    'RS': 'Rio Grande do Sul',
    'RO': 'Rondonia',
    'RR': 'Roraima',
    'SC': 'Santa Catarina',
    'SP': 'Sao Paulo',
    'SE': 'Sergipe',
    'TO': 'Tocantins',
    'DF': 'Federal District'
}

In [141]:
#new column for name state :
customers['state_name'] = customers['customer_state'].map(state_names)

In [142]:
# check the dublicate:
customers.duplicated().sum()

np.int64(0)

In [143]:
# check if there is null values :
customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
state_name                  0
dtype: int64

In [144]:
customers = customers[['customer_id', 'customer_zip_code_prefix', 'state_name']]

In [145]:
customers.head()

                        customer_id  customer_zip_code_prefix state_name
0  06b8999e2fba1a1fbc88172c00ba8bc7                     14409  Sao Paulo
1  18955e83d337fd6b2def6b18a428ac77                      9790  Sao Paulo
2  4e7b3e00288586ebd08712fdd0374a03                      1151  Sao Paulo
3  b2b6027bc5c5109e529d4dc6358b12c3                      8775  Sao Paulo
4  4f2d8ab171c80ec8364f7c12e35b23ad                     13056  Sao Paulo

In [146]:
customers.to_csv("olist_customers_cols_cleaned.csv", index=False)

## sellers dataset

In [167]:
# read the data 
sellers=pd.read_csv("olist_sellers_dataset.csv")

In [168]:
sellers.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

### columns : 
seller_id =   
seller unique identifier

seller_zip_code_prefix  =  
first 5 digits of seller zip code

seller_city  = 
seller city name

seller_state =  
seller state

##### new column:
seller_state_name = 
the name of each state

In [169]:
sellers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB

In [170]:
sellers.dtypes

seller_id                 object
seller_zip_code_prefix     int64
seller_city               object
seller_state              object
dtype: object

In [171]:
# To add new column (seller_state_name)
sellers["seller_state"].unique()

array(['SP', 'RJ', 'PE', 'PR', 'GO', 'SC', 'BA', 'DF', 'RS', 'MG', 'RN',
       'MT', 'CE', 'PB', 'AC', 'ES', 'RO', 'PI', 'MS', 'SE', 'MA', 'AM',
       'PA'], dtype=object)

In [172]:
sellers["seller_state_name"]= sellers['seller_state'].map(state_names)

In [173]:
# check duplicated :
sellers.duplicated().sum()

np.int64(0)

In [174]:
# check if there any null value:
sellers.isnull().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
seller_state_name         0
dtype: int64

In [175]:
sellers = sellers[['seller_id', 'seller_state_name' ,'seller_zip_code_prefix']]

In [176]:
# save it :
sellers.to_csv("olist_sellers_col_cleaned.csv", index=False)

## olist_geolocation_dataset.csv
## geolocation dataset

In [28]:
# read the data
geolocation=pd.read_csv("olist_geolocation_dataset.csv")

In [29]:
geolocation.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

### columns : 
geolocation_zip_code_prefix   =  
first 5 digits of zip code

geolocation_lat = 
latitude

geolocation_lng =  
longitude

geolocation_city  =  
city name


geolocation_state  =  
state

##### new column
state_name = 
the name of each state in brazil

In [30]:
# Explore data :
geolocation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object
 4   geolocation_state            1000163 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB

In [32]:
geolocation.describe(include="object")

       geolocation_city geolocation_state
count           1000163           1000163
unique             8011                27
top           sao paulo                SP
freq             135800            404268

In [37]:
# explore more data
geolocation["geolocation_city"].unique()

array(['sao paulo', 'são paulo', 'sao bernardo do campo', ..., 'ciríaco',
       'estação', 'vila lângaro'], shape=(8011,), dtype=object)

In [38]:
geolocation["geolocation_state"].unique()

array(['SP', 'RN', 'AC', 'RJ', 'ES', 'MG', 'BA', 'SE', 'PE', 'AL', 'PB',
       'CE', 'PI', 'MA', 'PA', 'AP', 'AM', 'RR', 'DF', 'GO', 'RO', 'TO',
       'MT', 'MS', 'RS', 'PR', 'SC'], dtype=object)

In [39]:
# add new column : name of states:
geolocation["state_name"] = geolocation["geolocation_state"].map(state_names)

In [40]:
geolocation["state_name"].value_counts()

state_name
Sao Paulo              404268
Minas Gerais           126336
Rio de Janeiro         121169
Rio Grande do Sul       61851
Parana                  57859
Santa Catarina          38328
Bahia                   36045
Goias                   20139
Espirito Santo          16748
Pernambuco              16432
Federal District        12986
Mato Grosso             12031
Ceara                   11674
Para                    10853
Mato Grosso do Sul      10431
Maranhao                 7853
Paraiba                  5538
Rio Grande do Norte      5041
Piaui                    4549
Alagoas                  4183
Tocantins                3576
Sergipe                  3563
Rondonia                 3478
Amazonas                 2432
Acre                     1301
Amapa                     853
Roraima                   646
Name: count, dtype: int64

In [41]:
# change the wrong city and state if the location not in Brazil :

In [42]:
# take the maximum and minimum for lat and lng for Brazil :
brazil = (geolocation["geolocation_lat"].between(-33.75, 5.27)& geolocation["geolocation_lng"].between(-73.99, -34.79))

#replace brazil city or state name with international
geolocation.loc[brazil == False, ["geolocation_city","geolocation_state", "state_name"]]="international"

In [43]:
#updated state name column:
geolocation["state_name"].value_counts()

state_name
Sao Paulo              404267
Minas Gerais           126334
Rio de Janeiro         121164
Rio Grande do Sul       61847
Parana                  57856
Santa Catarina          38328
Bahia                   36041
Goias                   20139
Espirito Santo          16746
Pernambuco              16421
Federal District        12986
Mato Grosso             12030
Ceara                   11674
Para                    10846
Mato Grosso do Sul      10431
Maranhao                 7853
Paraiba                  5537
Rio Grande do Norte      5041
Piaui                    4549
Alagoas                  4182
Tocantins                3576
Sergipe                  3563
Rondonia                 3478
Amazonas                 2432
Acre                     1301
Amapa                     853
Roraima                   646
international              42
Name: count, dtype: int64

In [44]:
# check dublicated : 
geolocation.duplicated().sum()

np.int64(261831)

In [45]:
geolocation["geolocation_zip_code_prefix"].duplicated().sum()

np.int64(981148)

In [46]:
# so, we drop the dublicated 
geolocation=geolocation.drop_duplicates()

In [47]:
# check again : 
geolocation.duplicated().sum()

np.int64(0)

In [48]:
# check null value: 
geolocation.isnull().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
state_name                     0
dtype: int64

In [49]:
# If there ia a customers not in Brazil :
# ckeck the longitude , latitude from geolocation dataset , then change the wrong state , then replace it in this data 
code = geolocation[geolocation["state_name"] == "international"]["geolocation_zip_code_prefix"]
customers.loc[customers["customer_zip_code_prefix"].isin(code), ["customer_city", "customer_state", "state_name"]] = "international"

In [50]:
# check :
customers["state_name"].value_counts()

state_name
Sao Paulo              41746
Rio de Janeiro         12847
Minas Gerais           11619
Rio Grande do Sul       5455
Parana                  5041
Santa Catarina          3637
Bahia                   3376
Federal District        2140
Espirito Santo          2032
Goias                   2020
Pernambuco              1652
Ceara                   1336
Para                     969
Mato Grosso              907
Maranhao                 747
Mato Grosso do Sul       715
Paraiba                  536
Piaui                    495
Rio Grande do Norte      485
Alagoas                  412
Sergipe                  350
Tocantins                280
Rondonia                 253
Amazonas                 148
Acre                      81
Amapa                     68
international             48
Roraima                   46
Name: count, dtype: int64

In [51]:
geolocation.to_csv("olist_geolocation_cols_cleaned.csv", index = False)

### Cleaning the Orders Dataset

In [57]:
orders = pd.read_csv("olist_orders_dataset.csv")

In [58]:
orders.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='object')

In [59]:
orders.shape

(99441, 8)

#### Fix the colum types

In [60]:
orders.dtypes

order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object

In [61]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [62]:
orders["order_purchase_timestamp"] = pd.to_datetime(orders["order_purchase_timestamp"])
orders["order_approved_at"] = pd.to_datetime(orders["order_approved_at"])
orders["order_delivered_carrier_date"] = pd.to_datetime(orders["order_delivered_carrier_date"])
orders["order_delivered_customer_date"] = pd.to_datetime(orders["order_delivered_customer_date"])
orders["order_estimated_delivery_date"] = pd.to_datetime(orders["order_estimated_delivery_date"])

In [63]:
orders.dtypes

order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

In [64]:
orders.describe()

,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
count,99441,99281,97658,96476,99441
mean,2017-12-31 08:43:12.776581120,2017-12-31 18:35:24.098800128,2018-01-04 21:49:48.138278656,2018-01-14 12:09:19.035542272,2018-01-24 03:08:37.730111232
min,2016-09-04 21:15:19,2016-09-15 12:16:38,2016-10-08 10:34:01,2016-10-11 13:46:32,2016-09-30 00:00:00
25%,2017-09-12 14:46:19,2017-09-12 23:24:16,2017-09-15 22:28:50.249999872,2017-09-25 22:07:22.249999872,2017-10-03 00:00:00
50%,2018-01-18 23:04:36,2018-01-19 11:36:13,2018-01-24 16:10:58,2018-02-02 19:28:10.500000,2018-02-15 00:00:00
75%,2018-05-04 15:42:16,2018-05-04 20:35:10,2018-05-08 13:37:45,2018-05-15 22:48:52.249999872,2018-05-25 00:00:00
max,2018-10-17 17:30:18,2018-09-03 17:40:06,2018-09-11 19:48:28,2018-10-17 13:22:46,2018-11-12 00:00:00

#### Check duplicates

In [65]:
orders.duplicated().sum()

np.int64(0)

#### Check nulls

In [66]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [67]:
orders.isnull().mean() * 100

order_id                         0.000000
customer_id                      0.000000
order_status                     0.000000
order_purchase_timestamp         0.000000
order_approved_at                0.160899
order_delivered_carrier_date     1.793023
order_delivered_customer_date    2.981668
order_estimated_delivery_date    0.000000
dtype: float64

##### Investegate the order_approved_at nulls

In [68]:
orders["order_status"].unique()

array(['delivered', 'invoiced', 'shipped', 'processing', 'unavailable',
       'canceled', 'created', 'approved'], dtype=object)

In [69]:
orders["order_status"].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

##### Check non-sence

In [70]:
fi3 = orders["order_delivered_carrier_date"] < orders["order_purchase_timestamp"]
orders[fi3]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
615,b9afddbdcfadc9a87b41a83271c3e888,85c6af75161b8b2b1af98e82b5a6a5a5,delivered,2018-08-16 13:50:48,2018-08-16 14:05:13,2018-08-16 13:27:00,2018-08-24 14:58:37,2018-09-04
1111,ad133696906f6a78826daa0911b7daec,e6f5b234bb0d847f10eebd70130c5d49,delivered,2018-06-15 15:41:22,2018-06-15 16:19:23,2018-06-15 14:52:00,2018-06-22 18:09:37,2018-07-18
1329,74e033208dc13a7b8127eb8e73d09b76,72fcbb1145f2889eddcba6d6c1d6c090,delivered,2018-05-02 10:48:44,2018-05-02 11:13:45,2018-05-02 09:49:00,2018-05-07 23:06:36,2018-05-29
1372,a6b58794fd2ba533359a76c08df576e3,ccd8e3459ad58ae538c9d2cf35532ba4,delivered,2018-05-14 15:18:23,2018-05-14 15:33:35,2018-05-14 13:46:00,2018-05-19 19:33:32,2018-06-08
1864,5792e0b1c8c8a2bf53af468c9a422c88,5c427f06e7fcf902e309743516e2c580,delivered,2018-07-26 13:25:14,2018-07-26 13:35:14,2018-07-26 12:42:00,2018-07-30 14:45:02,2018-08-09
...,...,...,...,...,...,...,...,...
98172,f7780ea2807db31691e83f0013294035,3088cc4bfafe311f1d84830808c2aa6d,delivered,2018-07-30 15:22:15,2018-07-30 15:35:16,2018-07-30 15:00:00,2018-08-02 18:32:30,2018-08-02
98430,d7646ffe8fdd9e7d9557f9f7cbf04530,f896e70d84f6db9a56b86a47dd8718f0,delivered,2018-05-04 14:50:37,2018-05-04 15:10:22,2018-05-04 14:48:00,2018-05-08 19:06:42,2018-05-16
98672,5ded8a3706eabd813685534724f066de,460316e38d4d241fc79d4f6729f8f7f6,delivered,2018-07-18 08:46:52,2018-07-18 09:01:48,2018-07-18 08:44:00,2018-07-25 13:53:17,2018-08-10
98780,d10046876c7d9f01613da59ffa6cb07f,6559cb5b365f173915f766fefcd86972,delivered,2018-07-18 16:14:16,2018-07-18 16:25:17,2018-07-18 15:34:00,2018-07-23 20:46:44,2018-08-07
99230,78008d03bd8ef7fcf1568728b316553c,043e3254e68daf7256bda1c9c03c2286,delivered,2018-07-03 13:11:13,2018-07-05 16:32:52,2018-07-03 12:57:00,2018-07-10 17:47:39,2018-07-23

In [71]:
orders['order_delivered_carrier_date'] = orders['order_delivered_carrier_date'].dt.date

In [72]:
orders['order_purchase_timestamp'] = orders['order_purchase_timestamp'].dt.date

In [73]:
fi4 = orders["order_delivered_customer_date"] < orders["order_delivered_carrier_date"]
orders[fi4]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
6437,a1abeb653a4d4cd1e142ccb8c82cd069,5f50465da00b7fed5dd1239f4ecf6e2c,delivered,2017-07-20,2017-07-21 06:43:14,2017-07-28,2017-07-25 19:32:56,2017-08-14
9553,383aa8b2724fe452d9ccd9934a8c628b,b1cb2f9d7a19480f3749e248db14d58f,delivered,2017-07-02,2017-07-02 21:10:20,2017-07-07,2017-07-06 14:27:51,2017-07-21
13487,cb1134f9010d242e9515ad1c78ec0c39,2fd33ac77677bd214b1882868317eeed,delivered,2017-07-16,2017-07-18 06:03:50,2017-07-20,2017-07-19 14:13:28,2017-08-08
14474,dceb62e8fa94b46006c9554fed743df0,2721900eb4e0f1cc2c836dd7bc1b1e11,delivered,2017-07-20,2017-07-22 11:45:11,2017-08-01,2017-07-26 18:09:10,2017-08-11
21338,8c78d01de3a9009e23d6877a7cc9be20,6cd7106899e59a1fbd0622d5f1efedf4,delivered,2016-10-08,2016-10-08 18:13:44,2016-10-26,2016-10-25 17:51:46,2016-11-30
22520,b27af682321527a6349f1761eb3f360c,9859dd92e872dbaa60ca3cd5f0d7ad07,delivered,2017-06-14,2017-06-14 20:30:08,2017-06-27,2017-06-26 15:45:35,2017-07-14
25646,e37f11cae9985ca58f0b56f268720537,3947a361301f2ff0f3223159a0f2701c,delivered,2017-07-26,2017-07-27 10:10:16,2017-08-01,2017-07-31 17:49:56,2017-08-24
27470,fa3e37584f4fdb1ded0e0de700dfcb4e,63be4feff10a0b1d85f2cfbf10df9754,delivered,2017-07-30,2017-07-30 19:45:09,2017-08-09,2017-08-01 21:13:01,2017-08-18
34939,c1e2bf2b7dd3309f2f5356c6b63968fa,e37d47e7eec62f08dc5deecc7d5532d6,delivered,2017-02-10,2017-02-10 10:30:13,2017-03-02,2017-02-14 15:15:57,2017-03-15
41636,b866af202be0692766081310cd4085e1,d1800078046ed2e5ae1b0792b695c56e,delivered,2017-01-27,2017-01-27 15:30:46,2017-02-20,2017-02-15 03:53:46,2017-04-17
45302,29941903985f944b0ffc49c479c1547d,b56ee98181afc3948a758d73a08423de,delivered,2017-05-29,2017-05-29 16:25:16,2017-06-09,2017-06-02 11:09:16,2017-06-23
49933,76458889992169d3135b264dc13aec67,999196dca58a3db3d966d8f148532010,delivered,2016-10-07,2016-10-07 11:24:43,2016-10-26,2016-10-20 18:03:17,2016-11-29
50373,0922ee1619de7b995648e5a8407afb91,8dab637615e9eae6d33ef5e48644d6d3,delivered,2017-07-11,2017-07-11 10:55:15,2017-07-14,2017-07-12 20:49:42,2017-08-14
58428,fbffbaaa30f4077e87ec6acdb835b278,a31e61974efff601345e65e5d6b7ff31,delivered,2017-07-30,2017-07-31 07:05:07,2017-08-04,2017-08-03 20:30:00,2017-08-18
71227,19feb5627c41ea1b36a8e50a469b3644,b8097c8f0c1f58ab56a53812a446a898,delivered,2016-10-07,2016-10-07 17:32:09,2016-10-26,2016-10-20 19:07:54,2016-12-01
74967,d5558a097766363b8e76b38c43332e8a,49a4fe701c3d30eac6c180908e665ebb,delivered,2017-02-04,2017-02-04 19:31:12,2017-02-15,2017-02-10 07:58:32,2017-03-01
76120,771c4f1f521f462e4b95619e648aaeab,d424b3ce4c850247e8c84ff8752de868,delivered,2017-03-22,2017-03-22 20:15:15,2017-03-30,2017-03-28 17:28:32,2017-04-12
78556,ea1dcb4757a844d2642547797bd5feb0,4999e129610251dec1e6fb712dc15171,delivered,2017-07-18,2017-07-18 13:50:23,2017-07-27,2017-07-25 19:43:10,2017-08-15
90373,99ad48402644a3968f2481defdc57947,abc709e0756f508111c68314b00cec25,delivered,2017-08-07,2017-08-07 17:20:06,2017-08-12,2017-08-10 21:22:31,2017-09-05
95634,f688669f48063536e082bb32d634cd46,691d28310063e5b36b732b117f2bcfc0,delivered,2016-10-07,2016-10-11 04:56:13,2016-10-21,2016-10-20 20:33:27,2016-11-29

In [74]:
orders = orders[~fi4]

In [75]:
fi4 = orders["order_delivered_customer_date"] < orders["order_delivered_carrier_date"]
orders[fi4]

Empty DataFrame
Columns: [order_id, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date]
Index: []

In [76]:
orders['order_delivered_customer_date'] = orders['order_delivered_customer_date'].dt.date

##### Check the order_delivered_carrier_date

In [77]:
orders[orders["order_delivered_carrier_date"].isnull()]["order_status"].unique()

array(['invoiced', 'processing', 'unavailable', 'canceled', 'created',
       'approved', 'delivered'], dtype=object)

In [78]:
fi1 = (orders["order_delivered_carrier_date"].isnull()== True) &  (orders["order_status"] == "delivered")
orders[fi1]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
73222,2aa91108853cecb43c84a5dc5b277475,afeb16c7f46396c0ed54acb45ccaaa40,delivered,2017-09-29,2017-09-29 09:07:16,NaT,2017-11-20,2017-11-14
92643,2d858f451373b04fb5c984a1cc2defaf,e08caf668d499a6d643dafd7c5cc498a,delivered,2017-05-25,2017-05-25 23:30:16,NaT,NaT,2017-06-23

In [79]:
orders= orders[~fi1]

In [80]:
fi1 = (orders["order_delivered_carrier_date"].isnull()== True) &  (orders["order_status"] == "delivered")
orders[fi1]

Empty DataFrame
Columns: [order_id, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date]
Index: []

##### Check the order_delivered_customer_date

In [81]:
orders[orders["order_delivered_customer_date"].isnull()]["order_status"].unique()

array(['invoiced', 'shipped', 'processing', 'unavailable', 'canceled',
       'delivered', 'created', 'approved'], dtype=object)

In [82]:
fi2 = (orders["order_delivered_customer_date"].isnull()== True) &  (orders["order_status"] == "delivered")
orders[fi2]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
3002,2d1e2d5bf4dc7227b3bfebb81328c15f,ec05a6d8558c6455f0cbbd8a420ad34f,delivered,2017-11-28,2017-11-28 17:56:40,2017-11-30,NaT,2017-12-18
20618,f5dd62b788049ad9fc0526e3ad11a097,5e89028e024b381dc84a13a3570decb4,delivered,2018-06-20,2018-06-20 07:19:05,2018-06-25,NaT,2018-07-16
43834,2ebdfc4f15f23b91474edf87475f108e,29f0540231702fda0cfdee0a310f11aa,delivered,2018-07-01,2018-07-01 17:15:12,2018-07-03,NaT,2018-07-30
79263,e69f75a717d64fc5ecdfae42b2e8e086,cfda40ca8dd0a5d486a9635b611b398a,delivered,2018-07-01,2018-07-01 22:15:14,2018-07-03,NaT,2018-07-30
82868,0d3268bad9b086af767785e3f0fc0133,4f1d63d35fb7c8999853b2699f5c7649,delivered,2018-07-01,2018-07-01 21:29:54,2018-07-03,NaT,2018-07-24
97647,ab7c89dc1bf4a1ead9d6ec1ec8968a84,dd1b84a7286eb4524d52af4256c0ba24,delivered,2018-06-08,2018-06-08 12:36:39,2018-06-12,NaT,2018-06-26
98038,20edc82cf5400ce95e1afacc25798b31,28c37425f1127d887d7337f284080a0f,delivered,2018-06-27,2018-06-27 16:29:30,2018-07-03,NaT,2018-07-19

In [83]:
orders= orders[~fi2]

In [84]:
fi2 = (orders["order_delivered_customer_date"].isnull()== True) &  (orders["order_status"] == "delivered")
orders[fi2]

Empty DataFrame
Columns: [order_id, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date]
Index: []

##### taking just the delivered orders

In [88]:
orders = orders[orders['order_status'] == 'delivered']

In [89]:
orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02,2017-10-02 11:07:15,2017-10-04,2017-10-10,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24,2018-07-26 03:24:27,2018-07-26,2018-08-07,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08,2018-08-08 08:55:23,2018-08-08,2018-08-17,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18,2017-11-18 19:45:59,2017-11-22,2017-12-02,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13,2018-02-13 22:20:29,2018-02-14,2018-02-16,2018-02-26
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09,2017-03-09 09:54:05,2017-03-10,2017-03-17,2017-03-28
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06,2018-02-06 13:10:37,2018-02-07,2018-02-28,2018-03-02
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27,2017-08-27 15:04:16,2017-08-28,2017-09-21,2017-09-27
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08,2018-01-08 21:36:21,2018-01-12,2018-01-25,2018-02-15
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08,2018-03-09 11:20:28,2018-03-09,2018-03-16,2018-04-03

### Save the cleaned data into the new csv file

In [90]:
orders.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='object')

In [91]:
orders = orders[['order_id', 'customer_id', 'order_purchase_timestamp', 'order_delivered_carrier_date',
       'order_delivered_customer_date'  ]]

In [92]:
orders

,order_id,customer_id,order_purchase_timestamp,order_delivered_carrier_date,order_delivered_customer_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,2017-10-02,2017-10-04,2017-10-10
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,2018-07-24,2018-07-26,2018-08-07
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,2018-08-08,2018-08-08,2018-08-17
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,2017-11-18,2017-11-22,2017-12-02
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,2018-02-13,2018-02-14,2018-02-16
...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,2017-03-09,2017-03-10,2017-03-17
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,2018-02-06,2018-02-07,2018-02-28
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,2017-08-27,2017-08-28,2017-09-21
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,2018-01-08,2018-01-12,2018-01-25
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,2018-03-08,2018-03-09,2018-03-16

In [93]:
orders.isnull().mean() * 100

order_id                         0.0
customer_id                      0.0
order_purchase_timestamp         0.0
order_delivered_carrier_date     0.0
order_delivered_customer_date    0.0
dtype: float64

In [94]:
orders.to_csv('olist_orders_cols_cleaned.csv', index=False)

### Cleaning the Order items Dataset

In [95]:
order_items = pd.read_csv("olist_order_items_dataset.csv")

In [96]:
order_items.shape

(112650, 7)

#### Fix the data types

In [97]:
order_items.dtypes

order_id                object
order_item_id            int64
product_id              object
seller_id               object
shipping_limit_date     object
price                  float64
freight_value          float64
dtype: object

In [98]:
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [103]:
order_items["shipping_limit_date"] = pd.to_datetime(order_items["shipping_limit_date"])

In [104]:
order_items.dtypes

order_id                       object
order_item_id                   int64
product_id                     object
seller_id                      object
shipping_limit_date    datetime64[ns]
price                         float64
freight_value                 float64
dtype: object

#### Check duplicate

In [105]:
order_items.duplicated().sum()

np.int64(0)

#### Check nulls

In [106]:
order_items.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

#### unvalid data

In [111]:
order_items.describe()

,order_item_id,shipping_limit_date,price,freight_value
count,112650.000000,112650,112650.000000,112650.000000
mean,1.197834,2018-01-07 15:36:52.192685312,120.653739,19.990320
min,1.000000,2016-09-19 00:15:34,0.850000,0.000000
25%,1.000000,2017-09-20 20:57:27.500000,39.900000,13.080000
50%,1.000000,2018-01-26 13:59:35,74.990000,16.260000
75%,1.000000,2018-05-10 14:34:00.750000128,134.900000,21.150000
max,21.000000,2020-04-09 22:35:08,6735.000000,409.680000
std,0.705124,NaN,183.633928,15.806405

### Save the cleaned data into the new csv file

In [112]:
order_items.columns

Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value'],
      dtype='object')

In [113]:
order_items = order_items[['order_id', 'order_item_id', 'product_id', 'seller_id', 'price', 'freight_value']]

In [114]:
order_items

,order_id,order_item_id,product_id,seller_id,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,199.90,18.14
...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,299.99,43.41
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,350.00,36.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,99.90,16.95
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,55.99,8.72
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,43.00,12.79

In [115]:
order_items.to_csv("olist_order_items_cols_cleaned.csv")

### Products Dataset Cleaning

In [116]:
products_df = pd.read_csv('olist_products_dataset.csv')

In [117]:
products_df.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [118]:
products_df.dtypes

product_id                     object
product_category_name          object
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

In [120]:
products_df.isnull().mean() * 100

product_id                    0.000000
product_category_name         1.851234
product_name_lenght           1.851234
product_description_lenght    1.851234
product_photos_qty            1.851234
product_weight_g              0.006070
product_length_cm             0.006070
product_height_cm             0.006070
product_width_cm              0.006070
dtype: float64

In [121]:
products_df.duplicated().sum()

np.int64(0)

In [122]:
products_df.describe()

,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
count,32341.000000,32341.000000,32341.000000,32949.000000,32949.000000,32949.000000,32949.000000
mean,48.476949,771.495285,2.188986,2276.472488,30.815078,16.937661,23.196728
std,10.245741,635.115225,1.736766,4282.038731,16.914458,13.637554,12.079047
min,5.000000,4.000000,1.000000,0.000000,7.000000,2.000000,6.000000
25%,42.000000,339.000000,1.000000,300.000000,18.000000,8.000000,15.000000
50%,51.000000,595.000000,1.000000,700.000000,25.000000,13.000000,20.000000
75%,57.000000,972.000000,3.000000,1900.000000,38.000000,21.000000,30.000000
max,76.000000,3992.000000,20.000000,40425.000000,105.000000,105.000000,118.000000

In [11]:
products_df[products_df['product_weight_g'] == 0] # we want tp check why min weight is 0 and if we can fix it

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
9769,81781c0fed9fe1ad6e8c81fca1e1cb08,cama_mesa_banho,51.0,529.0,1.0,0.0,30.0,25.0,30.0
13683,8038040ee2a71048d4bdbbdc985b69ab,cama_mesa_banho,48.0,528.0,1.0,0.0,30.0,25.0,30.0
14997,36ba42dd187055e1fbe943b2d11430ca,cama_mesa_banho,53.0,528.0,1.0,0.0,30.0,25.0,30.0
32079,e673e90efa65a5409ff4196c038bb5af,cama_mesa_banho,53.0,528.0,1.0,0.0,30.0,25.0,30.0

In [124]:
products_df = products_df[products_df['product_weight_g'] != 0]

In [125]:
products_df.columns

Index(['product_id', 'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='object')

In [126]:
products_df = products_df[['product_id', 'product_category_name','product_weight_g' ,'product_length_cm', 'product_height_cm', 'product_width_cm']]

In [127]:
products_df.to_csv('olist_products_cols_cleaned.csv', index=False)